-- +goose up

CREATE TABLE farms (
id BIGINT UNIQUE NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE DEFAUlT NULL
);

CREATE TABLE users(
id BIGINT UNIQUE NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
email varchar(255) NOT NULL,
password varchar(255) NOT NULL,
farm_id BIGINT,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE DEFAUlT NULL,

CONSTRAINT fk_farms_users
FOREIGN KEY (farm_id)
REFERENCES  farms(id)
ON DELETE SET NULL
);

CREATE UNIQUE INDEX unique_users_email_active
ON users (email)
WHERE deleted_at IS NULL;

CREATE TABLE fields (
id BIGINT UNIQUE NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL,
epsg_2100_boundary jsonb,
epsg_4326_boundary jsonb,
map_location jsonb,
field_location varchar(255),
area_in_meters FLOAT NOT NULL,
is_owned BOOLEAN NOT NULL DEFAULT FALSE,
farm_id BIGINT NOT NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE DEFAUlT NULL,

CONSTRAINT fk_farms_fields
FOREIGN KEY (farm_id)
REFERENCES farms(id)
ON DELETE CASCADE
);

CREATE UNIQUE INDEX unique_fields_name_farm_id_active
ON fields (name, farm_id)
WHERE deleted_at IS NULL;

CREATE TABLE supplies (
id BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
supply_type varchar(50) NOT NULL,
nickname varchar(255),
name varchar(255) NOT NULL,
measurement_unit varchar(50) NOT NULL,
farm_id BIGINT NOT NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE DEFAUlT NULL,

CONSTRAINT fk_farms_supplies
FOREIGN KEY (farm_id)
REFERENCES farms(id)
ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_supplies_unique_name_farm_id_active
ON supplies (name, farm_id)
WHERE deleted_at IS NULL;

CREATE TABLE supplies_prices (
id BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
price FLOAT NOT NULL,
quantity FLOAT NOT NULL,
buy_date TIMESTAMP WITH TIME ZONE,
supply_id BIGINT NOT NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE DEFAUlT NULL,

CONSTRAINT fk_supplies_prices_supplies
FOREIGN KEY (supply_id)
REFERENCES supplies(id)
ON DELETE CASCADE
);

CREATE TABLE supplies_details (
id BIGINT PRIMARY KEY UNIQUE GENERATED ALWAYS AS IDENTITY,
buy_date TIMESTAMP WITH TIME ZONE NOT NULL,
description TEXT NOT NULL, 
supply_id BIGINT NOT NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE DEFAUlT NULL,

CONSTRAINT fk_supplies_details_supplies
FOREIGN KEY (supply_id)
REFERENCES supplies(id)
ON DELETE CASCADE
);

CREATE TABLE jobs (
id BIGINT PRIMARY KEY UNIQUE GENERATED ALWAYS AS IDENTITY,
job_type varchar(100) NOT NULL,
description TEXT,
job_date TIMESTAMP WITH TIME ZONE NOT NULL,
field_id BIGINT NOT NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE DEFAUlT NULL,

CONSTRAINT fk_jobs_fields
FOREIGN KEY (field_id)
REFERENCES fields(id)
ON DELETE CASCADE
);


CREATE TABLE jobs_supplies(
id BIGINT PRIMARY KEY UNIQUE GENERATED ALWAYS AS IDENTITY,
quantity FLOAT NOT NULL,
job_id BIGINT,
supply_id BIGINT,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE DEFAUlT NULL,

CONSTRAINT fk_supplies_jobs_fields
FOREIGN KEY (job_id)
REFERENCES jobs(id)
ON DELETE CASCADE,

CONSTRAINT fk_supplies_jobs_supplies
FOREIGN KEY (supply_id)
REFERENCES supplies(id)
ON DELETE CASCADE,

UNIQUE (id,supply_id,deleted_at)
);

CREATE TABLE jobs_observations(
id BIGINT PRIMARY KEY UNIQUE GENERATED ALWAYS AS IDENTITY,
observation_date TIMESTAMP WITH TIME ZONE NOT NULL,
observations TEXT NOT NULL,
job_id BIGINT NOT NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE DEFAUlT NULL,

CONSTRAINT fk_jobs_observations_jobs
FOREIGN KEY (job_id)
REFERENCES jobs(id)
ON DELETE CASCADE
);

-- +goose down

DROP TABLE IF EXISTS jobs_observations;
DROP TABLE IF EXISTS jobs_supplies;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS supplies_details;
DROP TABLE IF EXISTS supplies_prices;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS fields;
DROP TABLE IF EXISTS supplies;
DROP TABLE IF EXISTS farms;
