-- +goose up
CREATE TABLE settings (
id BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE NOT NULL,
user_id BIGINT NOT NULL UNIQUE,
land_unit varchar(50) NOT NULL  DEFAULT 'm2',
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP WITH TIME ZONE,

CONSTRAINT fk_settings_user_id
FOREIGN KEY (user_id)
REFERENCES users(id)
ON DELETE CASCADE

);

-- +goose down
DROP TABLE settings;
