export const engToGreek = new Map<string, string>([
  ["chemicals", "Φάρμακά"],
  ["fertilizers", "Λιπάσματα"],
  ["KG", "Κιλά"],
  ["L", "Λίτρα"],
  ["spraying", "Ψεκασμός"],
  ["fertilizing", "Λίπανση"],
  ["planting", "Φύτευση"],
  ["sowing", "Σπορά"],
  ["irrigation", "Άρδευση Πότισμα"],
  ["transplanting", "Μεταφύτευση"],
  ["harvesting", "Συγκομιδή"],
  ["pruning", "Κλάδεμα"],
  ["weeding", "Ζιζανιοκτονία Βοτάνισμα"],
  ["soil preparation", "Προετοιμασία εδάφους"],
  ["plowing", "Όργωμα"],
  ["tilling", "Φρεζάρισμα"],
  ["cultivation", "Καλλιέργεια"],
  ["pest control", "Καταπολέμηση εχθρών"],
  ["disease control", "Καταπολέμηση ασθενειών"],
  ["crop monitoring", "Παρακολούθηση καλλιεργειών"],
  ["soil testing", "Εδαφολογικός έλεγχος"],
  ["fertilizer application", "Εφαρμογή λιπασμάτων"],
  ["pesticide application", "Εφαρμογή φυτοφαρμάκων"],
  ["equipment maintenance", "Συντήρηση εξοπλισμού"],
  ["field cleaning", "Καθαρισμός αγρού"],
  ["mulching", "Εδαφοκάλυψη"],
  ["thinning", "Αραίωμα"],
  ["post-harvest handling", "Μετασυλλεκτικοί χειρισμοί"],
]);
