export const engToGreek = new Map<string, string>([
  ["stremata", "Στρέμματα"],
  ["hectares", "Εκτάρια"],
  ["default", "Τετραγωνικά μέτρα"],

  ["chemicals", "Φάρμακά"],
  ["fertilizers", "Λιπάσματα"],
  ["seeds", "Σπόροι"],

  ["KG", "Κιλά"],
  ["L", "Λίτρα"],

  ["spraying", "Ψεκασμός"],
  ["fertilizing", "Λίπανση"],
  ["sowing", "Σπορά"],
  ["harvesting", "Συγκομιδή"],
  // ["irrigation", "Άρδευση Πότισμα"],
  // ["transplanting", "Μεταφύτευση"],
  // ["planting", "Φύτευση"],
  // ["pruning", "Κλάδεμα"],
  // ["weeding", "Ζιζανιοκτονία Βοτάνισμα"],
  // ["soil preparation", "Προετοιμασία εδάφους"],
  // ["plowing", "Όργωμα"],
  // ["tilling", "Φρεζάρισμα"],
  // ["cultivation", "Καλλιέργεια"],
  // ["pest control", "Καταπολέμηση εχθρών"],
  // ["disease control", "Καταπολέμηση ασθενειών"],
  // ["crop monitoring", "Παρακολούθηση καλλιεργειών"],
  // ["soil testing", "Εδαφολογικός έλεγχος"],
  // ["fertilizer application", "Εφαρμογή λιπασμάτων"],
  // ["pesticide application", "Εφαρμογή φυτοφαρμάκων"],
  // ["equipment maintenance", "Συντήρηση εξοπλισμού"],
  // ["field cleaning", "Καθαρισμός αγρού"],
  // ["mulching", "Εδαφοκάλυψη"],
  // ["thinning", "Αραίωμα"],
  // ["post-harvest handling", "Μετασυλλεκτικοί χειρισμοί"],
]);
