# Generated by Django 6.0 on 2025-12-18 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('farm_name', models.CharField()),
                ('farm_address', models.CharField(blank=True, null=True)),
                ('farm_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_farm_company', to='company.company')),
            ],
            options={
                'db_table': 'farm',
                'unique_together': {('farm_name', 'farm_company')},
            },
        ),
    ]
