# Generated by Django 6.0 on 2025-12-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_farm_farm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(),
        ),
    ]
