services:
  farm-server-test:
    container_name: farm-server-test
    build:
      context: .
      dockerfile: ./docker/test/server/Dockerfile
    ports:
      - "8010:8090"
    expose:
      - 8090
    env_file:
      - ./.test.env
    volumes:
      - ./server:/server
    networks:
      - "farm_test_nw"
      - farm_test_db_nw
    entrypoint: /data/start_server.sh
    command: go test ./... -coverpkg=./... -coverprofile=coverage.out -count=1
    # command: go run .
    depends_on:
      farm-test-db:
        condition: service_healthy

  farm-test-db:
    build:
      context: .
      dockerfile: ./docker/test/postgres/Dockerfile
    container_name: farm-test-db
    ports:
      - "1212:5432"
    expose:
      - "5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 1s
      timeout: 10s
      retries: 5
    env_file:
      - ./.test.env
    networks:
      - farm_test_db_nw

  farm-mailpit:
    container_name: farm-mailpit
    image: axllent/mailpit
    expose:
      - "8025"
      - "1025"
    ports:
      - "8025:8025"
    environment:
      # MP_MAX_MESSAGES: 5000
      # MP_DATABASE: /data/mailpit.db
      # MP_SMTP_REQUIRE_STARTTLS: true
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      # MP_SMTP_TLS_CERT: "sans:farm-mailpit"
      # MP_SMTP_TLS_KEY: "sans:farm-mailpit"
      MP_SMTP_TLS_CERT: /cert/cert.pem
      MP_SMTP_TLS_KEY: /cert/key.pem
    volumes:
      - ./docker/test/cert_for_tls:/cert
    networks:
      - farm_test_db_nw

  farm-client-test:
    build:
      context: .
      dockerfile: ./docker/test/client/Dockerfile
    container_name: farm-client-test
    volumes:
      - ./client:/client
    expose:
      - "3000"
    env_file:
      - ./.test.env

    networks:
      - "farm_test_nw"
    command: pnpm testb
    depends_on:
      - farm-server-test
networks:
  farm_test_nw:
  farm_test_db_nw:
