--
-- PostgreSQL database dump
--

--\restrict PUeOcfcrYz8gM8j4erKKtqsTVKvYQrqcvPceULfcDESkjPJ6qdTNXy6kXSm65av

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO xaosmaker;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO xaosmaker;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO xaosmaker;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.company (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    edited_at timestamp with time zone NOT NULL,
    company_name character varying NOT NULL
);


ALTER TABLE public.company OWNER TO xaosmaker;

--
-- Name: company_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public.company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO xaosmaker;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO xaosmaker;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO xaosmaker;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO xaosmaker;

--
-- Name: farm; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.farm (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    edited_at timestamp with time zone NOT NULL,
    farm_name character varying NOT NULL,
    farm_address character varying,
    farm_company_id bigint NOT NULL
);


ALTER TABLE public.farm OWNER TO xaosmaker;

--
-- Name: farm_field; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.farm_field (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    edited_at timestamp with time zone NOT NULL,
    field_name character varying NOT NULL,
    field_epsg_2100_boundary jsonb,
    field_epsg_4326_boundary jsonb,
    field_area_in_meters double precision NOT NULL,
    field_location jsonb,
    farm_field_id bigint NOT NULL
);


ALTER TABLE public.farm_field OWNER TO xaosmaker;

--
-- Name: farm_field_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public.farm_field ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.farm_field_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: farm_field_soil_properties; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.farm_field_soil_properties (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    edited_at timestamp with time zone NOT NULL,
    soil_ph double precision,
    soil_phosphorous double precision,
    soil_nitrogen double precision,
    soil_potasium double precision,
    farm_field_id bigint
);


ALTER TABLE public.farm_field_soil_properties OWNER TO xaosmaker;

--
-- Name: farm_field_soil_properties_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public.farm_field_soil_properties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.farm_field_soil_properties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: farm_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public.farm ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.farm_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public."user" (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    id bigint NOT NULL,
    email character varying(200) NOT NULL,
    first_name character varying(60) NOT NULL,
    last_name character varying(60) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    edited_at timestamp with time zone NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public."user" OWNER TO xaosmaker;

--
-- Name: user_groups; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.user_groups OWNER TO xaosmaker;

--
-- Name: user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public.user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profile; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.user_profile (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    edited_at timestamp with time zone NOT NULL,
    company_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_profile OWNER TO xaosmaker;

--
-- Name: user_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public.user_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_user_permissions; Type: TABLE; Schema: public; Owner: xaosmaker
--

CREATE TABLE public.user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.user_user_permissions OWNER TO xaosmaker;

--
-- Name: user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: xaosmaker
--

ALTER TABLE public.user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: farm farm_farm_name_farm_company_id_baf55163_uniq; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.farm
    ADD CONSTRAINT farm_farm_name_farm_company_id_baf55163_uniq UNIQUE (farm_name, farm_company_id);


--
-- Name: farm_field farm_field_field_name_farm_field_id_cb028be2_uniq; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.farm_field
    ADD CONSTRAINT farm_field_field_name_farm_field_id_cb028be2_uniq UNIQUE (field_name, farm_field_id);


--
-- Name: farm_field farm_field_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.farm_field
    ADD CONSTRAINT farm_field_pkey PRIMARY KEY (id);


--
-- Name: farm_field_soil_properties farm_field_soil_properties_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.farm_field_soil_properties
    ADD CONSTRAINT farm_field_soil_properties_pkey PRIMARY KEY (id);


--
-- Name: farm farm_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.farm
    ADD CONSTRAINT farm_pkey PRIMARY KEY (id);


--
-- Name: user user_email_key; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_key UNIQUE (email);


--
-- Name: user_groups user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.user_groups
    ADD CONSTRAINT user_groups_pkey PRIMARY KEY (id);


--
-- Name: user_groups user_groups_user_id_group_id_40beef00_uniq; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.user_groups
    ADD CONSTRAINT user_groups_user_id_group_id_40beef00_uniq UNIQUE (user_id, group_id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: user_profile user_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_pkey PRIMARY KEY (id);


--
-- Name: user_profile user_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_user_id_key UNIQUE (user_id);


--
-- Name: user_user_permissions user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.user_user_permissions
    ADD CONSTRAINT user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: user_user_permissions user_user_permissions_user_id_permission_id_7dc6e2e0_uniq; Type: CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.user_user_permissions
    ADD CONSTRAINT user_user_permissions_user_id_permission_id_7dc6e2e0_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: farm_farm_company_id_33501bbc; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX farm_farm_company_id_33501bbc ON public.farm USING btree (farm_company_id);


--
-- Name: farm_field_farm_field_id_5f8aa10f; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX farm_field_farm_field_id_5f8aa10f ON public.farm_field USING btree (farm_field_id);


--
-- Name: farm_field_soil_properties_farm_field_id_48a6b24d; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX farm_field_soil_properties_farm_field_id_48a6b24d ON public.farm_field_soil_properties USING btree (farm_field_id);


--
-- Name: user_email_54dc62b2_like; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX user_email_54dc62b2_like ON public."user" USING btree (email varchar_pattern_ops);


--
-- Name: user_groups_group_id_b76f8aba; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX user_groups_group_id_b76f8aba ON public.user_groups USING btree (group_id);


--
-- Name: user_groups_user_id_abaea130; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX user_groups_user_id_abaea130 ON public.user_groups USING btree (user_id);


--
-- Name: user_profile_company_id_0f6aee76; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX user_profile_company_id_0f6aee76 ON public.user_profile USING btree (company_id);


--
-- Name: user_user_permissions_permission_id_9deb68a3; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX user_user_permissions_permission_id_9deb68a3 ON public.user_user_permissions USING btree (permission_id);


--
-- Name: user_user_permissions_user_id_ed4a47ea; Type: INDEX; Schema: public; Owner: xaosmaker
--

CREATE INDEX user_user_permissions_user_id_ed4a47ea ON public.user_user_permissions USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_user_id; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: farm farm_farm_company_id_33501bbc_fk_company_id; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.farm
    ADD CONSTRAINT farm_farm_company_id_33501bbc_fk_company_id FOREIGN KEY (farm_company_id) REFERENCES public.company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: farm_field farm_field_farm_field_id_5f8aa10f_fk_farm_id; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.farm_field
    ADD CONSTRAINT farm_field_farm_field_id_5f8aa10f_fk_farm_id FOREIGN KEY (farm_field_id) REFERENCES public.farm(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: farm_field_soil_properties farm_field_soil_prop_farm_field_id_48a6b24d_fk_farm_fiel; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.farm_field_soil_properties
    ADD CONSTRAINT farm_field_soil_prop_farm_field_id_48a6b24d_fk_farm_fiel FOREIGN KEY (farm_field_id) REFERENCES public.farm_field(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_groups user_groups_group_id_b76f8aba_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.user_groups
    ADD CONSTRAINT user_groups_group_id_b76f8aba_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_groups user_groups_user_id_abaea130_fk_user_id; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.user_groups
    ADD CONSTRAINT user_groups_user_id_abaea130_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_profile user_profile_company_id_0f6aee76_fk_company_id; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_company_id_0f6aee76_fk_company_id FOREIGN KEY (company_id) REFERENCES public.company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_profile user_profile_user_id_8fdce8e2_fk_user_id; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_user_id_8fdce8e2_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_user_permissions user_user_permission_permission_id_9deb68a3_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.user_user_permissions
    ADD CONSTRAINT user_user_permission_permission_id_9deb68a3_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_user_permissions user_user_permissions_user_id_ed4a47ea_fk_user_id; Type: FK CONSTRAINT; Schema: public; Owner: xaosmaker
--

ALTER TABLE ONLY public.user_user_permissions
    ADD CONSTRAINT user_user_permissions_user_id_ed4a47ea_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

--\unrestrict PUeOcfcrYz8gM8j4erKKtqsTVKvYQrqcvPceULfcDESkjPJ6qdTNXy6kXSm65av

