# Generated by Django 6.0 on 2025-12-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppies',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField()),
                ('choices', models.CharField(choices=[('SPRAYING', 'Spraying'), ('FERTILIZER', 'Fertilizer')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
