export const engToGreek = new Map<string, string>([
  ["stremata", "Στρέμματα"],
  ["hectares", "Εκτάρια"],
  ["m2", "Τ.Μ"],
  ["chemicals", "Φάρμακά"],
  ["fertilizers", "Λιπάσματα"],
  ["seeds", "Σπόροι"],
  ["diesel", "Πετρέλαιο"],
  ["piece", "Τεμάχιο"],
  ["KG", "Κιλά"],
  ["L", "Λίτρα"],
  ["spraying", "Ψεκασμός"],
  ["fertilizing", "Λίπανση"],
  ["sowing", "Σπορά"],
  ["harvesting", "Συγκομιδή"],
]);
