# Generated by Django 6.0 on 2025-12-19 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmField',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField()),
                ('field_epsg_2100_boundary', models.JSONField(blank=True, null=True)),
                ('field_epsg_4326_boundary', models.JSONField(blank=True, null=True)),
                ('field_area_in_meters', models.FloatField()),
                ('field_location', models.JSONField(blank=True, null=True)),
                ('farm_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_farm_field', to='farm.farm')),
            ],
            options={
                'db_table': 'farm_field',
                'unique_together': {('field_name', 'farm_field')},
            },
        ),
        migrations.CreateModel(
            name='SoilProperties',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('soil_ph', models.FloatField(blank=True, null=True)),
                ('soil_phosphorous', models.FloatField(blank=True, null=True)),
                ('soil_nitrogen', models.FloatField(blank=True, null=True)),
                ('soil_potasium', models.FloatField(blank=True, null=True)),
                ('farm_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_farm_field', to='field.farmfield')),
            ],
            options={
                'db_table': 'farm_field_soil_properties',
            },
        ),
    ]
