# Generated by Django 6.0 on 2025-12-17 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmField',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField()),
                ('epsg_2100_boundary', models.JSONField(blank=True, null=True)),
                ('epsg_4326_boundary', models.JSONField(blank=True, null=True)),
                ('area_in_meters', models.FloatField()),
                ('farm_location', models.JSONField(blank=True, null=True)),
                ('farm_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='farm_field', to='farm.farm')),
            ],
            options={
                'unique_together': {('field_name', 'farm_field')},
            },
        ),
        migrations.CreateModel(
            name='SoilProperties',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('soil_ph', models.FloatField(blank=True, null=True)),
                ('soil_phosphorous', models.FloatField(blank=True, null=True)),
                ('soil_nitrogen', models.FloatField(blank=True, null=True)),
                ('soil_potasium', models.FloatField(blank=True, null=True)),
                ('farm_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='farm_field_soil', to='field.farmfield')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
