# Generated by Django 6.0 on 2025-12-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmfield',
            name='is_owned',
            field=models.BooleanField(default=False),
        ),
    ]
