// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: farm.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFarm = `-- name: CreateFarm :one
with ins_farm as (
INSERT INTO farms (created_at,updated_at,name)
VALUES(
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP,
    $1
  )RETURNING id, name, created_at, updated_at, deleted_at 
),
update_user as (

UPDATE users SET farm_id=(select id from ins_farm)
  WHERE users.id = $2
) select id, name, created_at, updated_at, deleted_at from ins_farm
`

type CreateFarmParams struct {
	Name string
	ID   int64
}

type CreateFarmRow struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) CreateFarm(ctx context.Context, arg CreateFarmParams) (CreateFarmRow, error) {
	row := q.db.QueryRow(ctx, createFarm, arg.Name, arg.ID)
	var i CreateFarmRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFarm = `-- name: GetFarm :one
SELECT id, name, created_at, updated_at, deleted_at
FROM farms
WHERE deleted_at IS NULL AND id = (
SELECT farm_id FROM users
where deleted_at IS NULL AND users.id = $1
)
`

func (q *Queries) GetFarm(ctx context.Context, id int64) (Farm, error) {
	row := q.db.QueryRow(ctx, getFarm, id)
	var i Farm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateFarm = `-- name: UpdateFarm :one
UPDATE farms
SET 
updated_at=CURRENT_TIMESTAMP,
name=COALESCE($1 ,name)
WHERE id=$2
RETURNING id, name, created_at, updated_at, deleted_at
`

type UpdateFarmParams struct {
	FarmName *string
	ID       int64
}

func (q *Queries) UpdateFarm(ctx context.Context, arg UpdateFarmParams) (Farm, error) {
	row := q.db.QueryRow(ctx, updateFarm, arg.FarmName, arg.ID)
	var i Farm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
