// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: farm.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFarm = `-- name: CreateFarm :one
with ins_farm as (
INSERT INTO "farm" (created_at,edited_at,farm_name)
VALUES(
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP,
    $1
  )RETURNING id, created_at, edited_at, farm_name 
),
update_user as (

UPDATE "user" SET farm_id=(select id from ins_farm)
  WHERE "user".id = $2
) select id, created_at, edited_at, farm_name from ins_farm
`

type CreateFarmParams struct {
	FarmName string
	ID       int64
}

type CreateFarmRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	EditedAt  pgtype.Timestamptz
	FarmName  string
}

func (q *Queries) CreateFarm(ctx context.Context, arg CreateFarmParams) (CreateFarmRow, error) {
	row := q.db.QueryRow(ctx, createFarm, arg.FarmName, arg.ID)
	var i CreateFarmRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.FarmName,
	)
	return i, err
}

const getFarm = `-- name: GetFarm :one
SELECT id, created_at, edited_at, farm_name 
FROM "farm" 
WHERE id = (
SELECT farm_id FROM "user"
where "user".id = $1
)
`

func (q *Queries) GetFarm(ctx context.Context, id int64) (Farm, error) {
	row := q.db.QueryRow(ctx, getFarm, id)
	var i Farm
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.FarmName,
	)
	return i, err
}

const updateFarm = `-- name: UpdateFarm :one
UPDATE "farm" 
SET 
edited_at=CURRENT_TIMESTAMP,
farm_name=COALESCE($1 ,farm_name)
WHERE id=$2
RETURNING id, created_at, edited_at, farm_name
`

type UpdateFarmParams struct {
	FarmName *string
	ID       int64
}

func (q *Queries) UpdateFarm(ctx context.Context, arg UpdateFarmParams) (Farm, error) {
	row := q.db.QueryRow(ctx, updateFarm, arg.FarmName, arg.ID)
	var i Farm
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.FarmName,
	)
	return i, err
}
