// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fields.sql

package db

import (
	"context"
	"encoding/json"
)

const createField = `-- name: CreateField :one
INSERT INTO "farm_field"(
  created_at,
  edited_at, 
  field_name,
  field_epsg_2100_boundary, 
  field_epsg_4326_boundary, 
  field_area_in_meters, 
  field_location, 
  farm_field_id,
  is_owned 
)VALUES(
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP,
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
  )RETURNING id, created_at, edited_at, field_name, field_epsg_2100_boundary, field_epsg_4326_boundary, field_area_in_meters, field_location, farm_field_id, is_owned
`

type CreateFieldParams struct {
	FieldName             string
	FieldEpsg2100Boundary *json.RawMessage
	FieldEpsg4326Boundary *json.RawMessage
	FieldAreaInMeters     float64
	FieldLocation         *json.RawMessage
	FarmFieldID           int64
	IsOwned               bool
}

func (q *Queries) CreateField(ctx context.Context, arg CreateFieldParams) (FarmField, error) {
	row := q.db.QueryRow(ctx, createField,
		arg.FieldName,
		arg.FieldEpsg2100Boundary,
		arg.FieldEpsg4326Boundary,
		arg.FieldAreaInMeters,
		arg.FieldLocation,
		arg.FarmFieldID,
		arg.IsOwned,
	)
	var i FarmField
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.FieldName,
		&i.FieldEpsg2100Boundary,
		&i.FieldEpsg4326Boundary,
		&i.FieldAreaInMeters,
		&i.FieldLocation,
		&i.FarmFieldID,
		&i.IsOwned,
	)
	return i, err
}

const getAllFields = `-- name: GetAllFields :many
select id, created_at, edited_at, field_name, field_epsg_2100_boundary, field_epsg_4326_boundary, field_area_in_meters, field_location, farm_field_id, is_owned from "farm_field"
`

func (q *Queries) GetAllFields(ctx context.Context) ([]FarmField, error) {
	rows, err := q.db.Query(ctx, getAllFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FarmField
	for rows.Next() {
		var i FarmField
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.FieldName,
			&i.FieldEpsg2100Boundary,
			&i.FieldEpsg4326Boundary,
			&i.FieldAreaInMeters,
			&i.FieldLocation,
			&i.FarmFieldID,
			&i.IsOwned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
