// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthGroup struct {
	ID   int32
	Name string
}

type AuthGroupPermission struct {
	ID           int64
	GroupID      int32
	PermissionID int32
}

type AuthPermission struct {
	ID            int32
	Name          string
	ContentTypeID int32
	Codename      string
}

type DjangoAdminLog struct {
	ID            int32
	ActionTime    pgtype.Timestamptz
	ObjectID      *string
	ObjectRepr    string
	ActionFlag    int16
	ChangeMessage string
	ContentTypeID *int32
	UserID        int64
}

type DjangoContentType struct {
	ID       int32
	AppLabel string
	Model    string
}

type DjangoMigration struct {
	ID      int64
	App     string
	Name    string
	Applied pgtype.Timestamptz
}

type DjangoSession struct {
	SessionKey  string
	SessionData string
	ExpireDate  pgtype.Timestamptz
}

type Farm struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	EditedAt  pgtype.Timestamptz
	FarmName  string
}

type FarmField struct {
	ID                    int64
	CreatedAt             pgtype.Timestamptz
	EditedAt              pgtype.Timestamptz
	FieldName             string
	FieldEpsg2100Boundary *json.RawMessage
	FieldEpsg4326Boundary *json.RawMessage
	FieldAreaInMeters     float64
	FieldLocation         *json.RawMessage
	FarmFieldID           int64
	IsOwned               bool
}

type FarmFieldSoilProperty struct {
	ID              int64
	CreatedAt       pgtype.Timestamptz
	EditedAt        pgtype.Timestamptz
	SoilPh          *float64
	SoilPhosphorous *float64
	SoilNitrogen    *float64
	SoilPotasium    *float64
	FarmFieldID     *int64
}

type User struct {
	Password    string
	LastLogin   pgtype.Timestamptz
	IsSuperuser bool
	ID          int64
	Email       string
	FirstName   string
	LastName    string
	CreatedAt   pgtype.Timestamptz
	EditedAt    pgtype.Timestamptz
	IsStaff     bool
	IsActive    bool
	FarmID      *int64
}

type UserGroup struct {
	ID      int64
	UserID  int64
	GroupID int32
}

type UserUserPermission struct {
	ID           int64
	UserID       int64
	PermissionID int32
}
