// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"
)

type Farm struct {
	ID        int64
	Name      string
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
}

type Field struct {
	ID               int64
	Name             string
	Epsg2100Boundary *json.RawMessage
	Epsg4326Boundary *json.RawMessage
	MapLocation      *json.RawMessage
	FieldLocation    *string
	AreaInMeters     float64
	IsOwned          bool
	FarmID           int64
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	DeletedAt        *time.Time
}

type Job struct {
	ID           int64
	JobType      string
	Description  *string
	JobDate      time.Time
	AreaInMeters float64
	Boundary     *json.RawMessage
	SeasonID     int64
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	DeletedAt    *time.Time
}

type JobsObservation struct {
	ID              int64
	ObservationDate time.Time
	Observations    string
	JobID           int64
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
	DeletedAt       *time.Time
}

type JobsSupply struct {
	ID        int64
	Quantity  float64
	JobID     *int64
	SupplyID  *int64
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
}

type Season struct {
	ID           int64
	FieldID      int64
	Name         *string
	StartSeason  time.Time
	FinishSeason *time.Time
	Crop         int64
	Boundary     *json.RawMessage
	AreaInMeters float64
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	DeletedAt    *time.Time
}

type Setting struct {
	ID        int64
	UserID    int64
	LandUnit  string
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
}

type SuppliesDetail struct {
	ID          int64
	BuyDate     time.Time
	Description string
	SupplyID    int64
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
	DeletedAt   *time.Time
}

type SuppliesPrice struct {
	ID        int64
	Price     float64
	Quantity  float64
	BuyDate   *time.Time
	SupplyID  int64
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
}

type Supply struct {
	ID              int64
	SupplyType      string
	Nickname        *string
	Name            string
	MeasurementUnit string
	FarmID          int64
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
	DeletedAt       *time.Time
}

type User struct {
	ID        int64
	Email     string
	Password  string
	FarmID    *int64
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
	IsActive  bool
}
