// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Farm struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Field struct {
	ID               int64
	Name             string
	Epsg2100Boundary *json.RawMessage
	Epsg4326Boundary *json.RawMessage
	FieldLocation    *json.RawMessage
	AreaInMeters     float64
	IsOwned          bool
	FarmID           int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type Job struct {
	ID          int64
	JobType     string
	Description *string
	JobDate     pgtype.Timestamptz
	FieldID     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type JobsObservation struct {
	ID              int64
	ObservationDate pgtype.Timestamptz
	Observations    string
	JobID           int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type JobsSupply struct {
	ID        int64
	Quantity  float64
	JobID     *int64
	SupplyID  *int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type SuppliesDetail struct {
	ID          int64
	BuyDate     pgtype.Timestamptz
	Description string
	SupplyID    int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type SuppliesPrice struct {
	ID        int64
	Price     float64
	Quantity  float64
	BuyDate   pgtype.Timestamptz
	SupplyID  int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Supply struct {
	ID              int64
	SupplyType      string
	Nickname        *string
	Name            string
	MeasurementUnit string
	FarmID          int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type User struct {
	ID        int64
	Email     string
	Password  string
	FarmID    *int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
