// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seasons.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSeasonsByFieldId = `-- name: GetSeasonsByFieldId :many
SELECT 
s.id,s.field_id,s.name,s.start_season,s.finish_season,s.crop,s.boundary,
  s.area_in_meters,s.created_at,s.updated_at,s.deleted_at,
  supplies.name as crop_name
FROM seasons s
JOIN supplies
ON supplies.id = crop
WHERE s.deleted_at IS NULL AND supplies.deleted_at IS NULL
AND s.field_id = $1
`

type GetSeasonsByFieldIdRow struct {
	ID           int64
	FieldID      int64
	Name         *string
	StartSeason  pgtype.Timestamptz
	FinishSeason pgtype.Timestamptz
	Crop         int64
	Boundary     *json.RawMessage
	AreaInMeters float64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	CropName     string
}

func (q *Queries) GetSeasonsByFieldId(ctx context.Context, fieldID int64) ([]GetSeasonsByFieldIdRow, error) {
	rows, err := q.db.Query(ctx, getSeasonsByFieldId, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeasonsByFieldIdRow
	for rows.Next() {
		var i GetSeasonsByFieldIdRow
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.Name,
			&i.StartSeason,
			&i.FinishSeason,
			&i.Crop,
			&i.Boundary,
			&i.AreaInMeters,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CropName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
