// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
)

const getUserSettings = `-- name: GetUserSettings :one
SELECT id, user_id, land_unit, created_at, updated_at, deleted_at FROM settings
WHERE user_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, userID int64) (Setting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LandUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
update settings set land_unit=$1
WHERE user_id = $2
returning id, user_id, land_unit, created_at, updated_at, deleted_at
`

type UpdateSettingsParams struct {
	LandUnit string
	UserID   int64
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSettings, arg.LandUnit, arg.UserID)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LandUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
