// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: supplies.sql

package db

import (
	"context"
)

const createSupplies = `-- name: CreateSupplies :one
INSERT INTO supplies (
supply_type,
nickname,
name,
measurement_unit,
farm_id,
created_at,
updated_at
)VALUES(
  $1,
  $2,
  $3,
  $4,
  $5,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
  ) RETURNING id, supply_type, nickname, name, measurement_unit, farm_id, created_at, updated_at, deleted_at
`

type CreateSuppliesParams struct {
	SupplyType      string
	Nickname        *string
	Name            string
	MeasurementUnit string
	FarmID          int64
}

func (q *Queries) CreateSupplies(ctx context.Context, arg CreateSuppliesParams) (Supply, error) {
	row := q.db.QueryRow(ctx, createSupplies,
		arg.SupplyType,
		arg.Nickname,
		arg.Name,
		arg.MeasurementUnit,
		arg.FarmID,
	)
	var i Supply
	err := row.Scan(
		&i.ID,
		&i.SupplyType,
		&i.Nickname,
		&i.Name,
		&i.MeasurementUnit,
		&i.FarmID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllSupplies = `-- name: GetAllSupplies :many
SELECT id, supply_type, nickname, name, measurement_unit, farm_id, created_at, updated_at, deleted_at FROM supplies
WHERE farm_id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetAllSupplies(ctx context.Context, farmID int64) ([]Supply, error) {
	rows, err := q.db.Query(ctx, getAllSupplies, farmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supply
	for rows.Next() {
		var i Supply
		if err := rows.Scan(
			&i.ID,
			&i.SupplyType,
			&i.Nickname,
			&i.Name,
			&i.MeasurementUnit,
			&i.FarmID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
