// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :exec
WITH new_user AS (
INSERT INTO users (
created_at,
updated_at,
email,
password
)values(
CURRENT_TIMESTAMP,
CURRENT_TIMESTAMP,
    $1,
    $2
)RETURNING id, email, password, farm_id, created_at, updated_at, deleted_at, is_active
)
INSERT INTO settings(
user_id
)
select id from new_user
`

type CreateUserParams struct {
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Email, arg.Password)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
select id, email, password, farm_id, created_at, updated_at, deleted_at, is_active from users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.FarmID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBYId = `-- name: GetUserBYId :one
SELECT id, email, password, farm_id, created_at, updated_at, deleted_at, is_active FROM users
WHERE users.deleted_at IS NULL AND id = $1
`

func (q *Queries) GetUserBYId(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserBYId, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FarmID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsActive,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, farm_id, created_at, updated_at, deleted_at, is_active FROM users
WHERE users.deleted_at IS NULL AND users.is_active = TRUE AND email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FarmID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsActive,
	)
	return i, err
}

const getUserByIdWithSettings = `-- name: GetUserByIdWithSettings :one
SELECT users.id, email, password, farm_id, users.created_at, users.updated_at, users.deleted_at, is_active, settings.id, user_id, land_unit, settings.created_at, settings.updated_at, settings.deleted_at FROM users
JOIN settings
ON users.id = settings.user_id
WHERE users.deleted_at IS NULL AND users.id = $1
`

type GetUserByIdWithSettingsRow struct {
	ID          int64
	Email       string
	Password    string
	FarmID      *int64
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
	DeletedAt   *time.Time
	IsActive    bool
	ID_2        int64
	UserID      int64
	LandUnit    string
	CreatedAt_2 *time.Time
	UpdatedAt_2 *time.Time
	DeletedAt_2 *time.Time
}

func (q *Queries) GetUserByIdWithSettings(ctx context.Context, id int64) (GetUserByIdWithSettingsRow, error) {
	row := q.db.QueryRow(ctx, getUserByIdWithSettings, id)
	var i GetUserByIdWithSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FarmID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsActive,
		&i.ID_2,
		&i.UserID,
		&i.LandUnit,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.DeletedAt_2,
	)
	return i, err
}
